import Head from 'next/head';
import Link from 'next/link';
import RootLayout from './layout';
import styles from './Home.module.css';

const Home = () => {
  return (
    <RootLayout>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1>Welcome to My Next.js App!</h1>
        <p>This is a simple Next.js application using TypeScript.</p>
        <Link href="/about" className={styles.link}>About</Link>
      </main>

      <footer className={styles.footer}>
        <p>Powered by Next.js</p>
      </footer>
    </RootLayout>
  );
};

export default Home;
